test

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -67,5 +67,5 @@ jobs:
         run: |
           [[ -n "${{ steps.changed-files.outputs.all_changed_files }}" ]] &&
           (echo "${{ steps.changed-files.outputs.all_changed_files }}" | xargs isort --check --diff &&
-          echo "::error error!!!!!") ||
+          echo "::error file=app.js,line=1::Missing semicolon") ||
           echo "0 Python files changed."
